import Link from "next/link";
import { cmsStatuses } from "@/lib/admin/cms-content-options";
import { listAdminFaqCmsEntries } from "@/server/admin/cms-faqs";

export default async function AdminFaqsPage({ searchParams }: { searchParams?: Promise<Record<string, string | string[] | undefined>> }) {
  const params = (await searchParams) ?? {};
  const result = await listAdminFaqCmsEntries({ status: String(params.status ?? ""), category: String(params.category ?? ""), archived: String(params.archived ?? "active"), search: String(params.search ?? "") });
  const items = result.ok ? result.items : [];
  const categories = Array.from(new Set(items.map((item) => item.category).filter((category): category is string => Boolean(category)))).sort();
  return <div className="space-y-6">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-cyan-700">FAQ CMS pilot</p><h2 className="text-2xl font-bold text-slate-950">FAQ CMS entries</h2><p className="mt-2 max-w-3xl text-sm text-slate-600">Admin-only FAQ draft and revision workflow using the generic CMS core tables. Public FAQ rendering is not connected to CMS yet.</p></div><Link href="/admin/content/faqs/new" className="rounded-full bg-slate-950 px-4 py-2 text-sm font-semibold text-white">New FAQ draft</Link></div>
    <div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm font-semibold text-amber-900">Warning: Public FAQ rendering is not connected to CMS yet. This pilot does not publish public FAQs.</div>
    <form className="grid gap-3 rounded-2xl border bg-white p-4 text-sm md:grid-cols-4"><input name="search" placeholder="Search question/content key" defaultValue={String(params.search ?? "")} className="rounded-lg border p-2"/><select name="status" defaultValue={String(params.status ?? "")} className="rounded-lg border p-2"><option value="">Any status</option>{cmsStatuses.map((status) => <option key={status} value={status}>{status}</option>)}</select><select name="archived" defaultValue={String(params.archived ?? "active")} className="rounded-lg border p-2"><option value="active">Active</option><option value="archived">Archived</option><option value="all">All</option></select><select name="category" defaultValue={String(params.category ?? "")} className="rounded-lg border p-2"><option value="">Any category</option>{categories.map((category) => <option key={category} value={category}>{category}</option>)}</select><button className="rounded-full border px-4 py-2 font-semibold md:col-span-4">Apply filters</button></form>
    {!result.ok ? <p className="rounded-2xl border border-red-200 bg-red-50 p-4 text-red-700">FAQ CMS entries could not be loaded.</p> : items.length === 0 ? <p className="rounded-2xl border bg-white p-5 text-slate-600">No FAQ CMS entries yet.</p> : <div className="overflow-x-auto rounded-2xl border bg-white"><table className="min-w-full divide-y text-sm"><thead className="bg-slate-50"><tr>{["Question EN","Question AR","Content key","Status","Rev","Category","Order","Featured","Updated","Archived"].map((h) => <th key={h} className="px-3 py-2 text-left">{h}</th>)}</tr></thead><tbody className="divide-y">{items.map((item) => <tr key={item.id}><td className="px-3 py-2"><Link className="font-semibold text-cyan-700" href={`/admin/content/faqs/${item.id}`}>{item.questionEn ?? "—"}</Link></td><td className="px-3 py-2">{item.questionAr ?? "—"}</td><td className="px-3 py-2 font-mono text-xs">{item.contentKey}</td><td className="px-3 py-2">{item.status}</td><td className="px-3 py-2">{item.currentRevisionNumber ?? "—"}</td><td className="px-3 py-2">{item.category ?? "—"}</td><td className="px-3 py-2">{item.displayOrder}</td><td className="px-3 py-2">{item.isFeatured ? "Yes" : "No"}</td><td className="px-3 py-2">{new Date(item.updatedAt).toLocaleString()}</td><td className="px-3 py-2">{item.isArchived ? "Archived" : "Active"}</td></tr>)}</tbody></table></div>}
  </div>;
}
