import type { OmanGeoRouteEntity } from '@/config/geo/route-contract';

export type OmanGeoEditorialBlockKey =
  | 'hero-summary'
  | 'local-context'
  | 'care-access'
  | 'nearby-areas'
  | 'editorial-disclaimer';

export type OmanGeoEditorialReadinessEntityContract = {
  entity: OmanGeoRouteEntity;
  minimumEnglishWords: number;
  minimumArabicWords: number;
  requiredBlocks: readonly OmanGeoEditorialBlockKey[];
  requiresDistinctLocaleCopy: boolean;
  placeholderCopyAllowed: boolean;
  aiMedicalAdviceAllowed: boolean;
  mohVerificationClaimsAllowed: boolean;
  providerRankingClaimsAllowed: boolean;
  humanReviewRequired: boolean;
};

export const OMAN_GEO_EDITORIAL_READINESS_CONTRACT_VERSION = 'v1' as const;

const requiredBlocks = [
  'hero-summary',
  'local-context',
  'care-access',
  'nearby-areas',
  'editorial-disclaimer',
] as const;

export const OMAN_GEO_EDITORIAL_READINESS_CONTRACTS: readonly OmanGeoEditorialReadinessEntityContract[] = [
  {
    entity: 'governorate',
    minimumEnglishWords: 120,
    minimumArabicWords: 120,
    requiredBlocks,
    requiresDistinctLocaleCopy: true,
    placeholderCopyAllowed: false,
    aiMedicalAdviceAllowed: false,
    mohVerificationClaimsAllowed: false,
    providerRankingClaimsAllowed: false,
    humanReviewRequired: true,
  },
  {
    entity: 'wilayat',
    minimumEnglishWords: 90,
    minimumArabicWords: 90,
    requiredBlocks,
    requiresDistinctLocaleCopy: true,
    placeholderCopyAllowed: false,
    aiMedicalAdviceAllowed: false,
    mohVerificationClaimsAllowed: false,
    providerRankingClaimsAllowed: false,
    humanReviewRequired: true,
  },
  {
    entity: 'area',
    minimumEnglishWords: 70,
    minimumArabicWords: 70,
    requiredBlocks,
    requiresDistinctLocaleCopy: true,
    placeholderCopyAllowed: false,
    aiMedicalAdviceAllowed: false,
    mohVerificationClaimsAllowed: false,
    providerRankingClaimsAllowed: false,
    humanReviewRequired: true,
  },
] as const;

export const OMAN_GEO_EDITORIAL_READINESS_CONTRACT = {
  version: OMAN_GEO_EDITORIAL_READINESS_CONTRACT_VERSION,
  contracts: OMAN_GEO_EDITORIAL_READINESS_CONTRACTS,
  currentEditorialEvidenceAvailable: false,
  promotionRequiresHumanReview: true,
  promotionRequiresArabicAndEnglishCopy: true,
  currentIndexPromotionAllowed: false,
  currentSitemapPromotionAllowed: false,
  nonGoals: [
    'No editorial content is generated by this contract.',
    'No AI medical advice is allowed by this contract.',
    'No MOH verification claims are allowed by this contract.',
    'No provider ranking claims are allowed by this contract.',
    'No geo route becomes indexable by this contract.',
  ],
} as const;
