import type { OmanGeoRouteEntity } from '@/config/geo/route-contract';
import type { OmanGeoEditorialBlockKey } from '@/config/geo/editorial-readiness-contract';

export type OmanGeoEditorialContentLocale = 'en' | 'ar';

export type OmanGeoEditorialContentStatus = 'contract-only' | 'draft' | 'ready-for-review' | 'published';

export type OmanGeoEditorialContentBlock = {
  key: OmanGeoEditorialBlockKey;
  content: string;
};

export type OmanGeoEditorialContentEntry = {
  entity: OmanGeoRouteEntity;
  slug: string;
  locale: OmanGeoEditorialContentLocale;
  status: OmanGeoEditorialContentStatus;
  blocks: readonly OmanGeoEditorialContentBlock[];
  reviewedByHuman: boolean;
};

export const OMAN_GEO_EDITORIAL_CONTENT_CONTRACT_VERSION = 'v1' as const;

export const OMAN_GEO_EDITORIAL_CONTENT_REQUIRED_BLOCKS: readonly OmanGeoEditorialBlockKey[] = [
  'hero-summary',
  'local-context',
  'care-access',
  'nearby-areas',
  'editorial-disclaimer',
] as const;

export const OMAN_GEO_EDITORIAL_CONTENT_LOCALES: readonly OmanGeoEditorialContentLocale[] = ['en', 'ar'] as const;

export const OMAN_GEO_EDITORIAL_CONTENT_REGISTRY: readonly OmanGeoEditorialContentEntry[] = [] as const;

export const OMAN_GEO_EDITORIAL_CONTENT_CONTRACT = {
  version: OMAN_GEO_EDITORIAL_CONTENT_CONTRACT_VERSION,
  status: 'contract-only' as OmanGeoEditorialContentStatus,
  locales: OMAN_GEO_EDITORIAL_CONTENT_LOCALES,
  requiredBlocks: OMAN_GEO_EDITORIAL_CONTENT_REQUIRED_BLOCKS,
  registry: OMAN_GEO_EDITORIAL_CONTENT_REGISTRY,
  registryEnabled: false,
  currentPublishedContentCount: 0,
  currentDraftContentCount: 0,
  currentReadyForReviewContentCount: 0,
  currentContentEvidenceAvailable: false,
  promotionRequiresHumanReview: true,
  promotionRequiresDistinctLocaleCopy: true,
  placeholderCopyAllowed: false,
  aiMedicalAdviceAllowed: false,
  mohVerificationClaimsAllowed: false,
  providerRankingClaimsAllowed: false,
  nonGoals: [
    'No editorial copy is published by this contract.',
    'No draft editorial copy is added by this contract.',
    'No route becomes indexable by this contract.',
    'No route becomes sitemap-eligible by this contract.',
    'No JSON-LD is generated by this contract.',
  ],
} as const;
