import type { OmanGeoRouteEntity } from '@/config/geo/route-contract';

export type OmanGeoEvidenceRegistryStatus = 'registry-disabled' | 'draft' | 'ready-for-review' | 'approved';
export type OmanGeoEvidenceKind = 'provider-inventory' | 'editorial-content' | 'qa-evidence' | 'promotion-review';
export type OmanGeoEvidenceSourceType = 'manual-review' | 'future-cms' | 'future-provider-query' | 'future-qa-run';

export type OmanGeoEvidenceRegistryEntry = {
  id: string;
  entity: OmanGeoRouteEntity;
  slug: string;
  locale: 'en' | 'ar' | 'all';
  kind: OmanGeoEvidenceKind;
  sourceType: OmanGeoEvidenceSourceType;
  status: OmanGeoEvidenceRegistryStatus;
  reviewedByHuman: boolean;
  reviewerRole: 'seo-lead' | 'medical-editor' | 'technical-reviewer' | null;
  reviewedAt: string | null;
  evidenceSummary: string;
  promotionAllowed: boolean;
};

export type OmanGeoEvidenceRegistryEntityContract = {
  entity: OmanGeoRouteEntity;
  registryEnabled: boolean;
  requiredEvidenceKinds: readonly OmanGeoEvidenceKind[];
  minimumApprovedEvidenceEntries: number;
  approvedEvidenceEntries: number;
  promotionAllowed: boolean;
  noindexRemovalAllowed: boolean;
  sitemapPromotionAllowed: boolean;
  jsonLdAllowed: boolean;
  indexPromotionAllowed: boolean;
};

export const OMAN_GEO_EVIDENCE_REGISTRY_CONTRACT_VERSION = 'v1' as const;

export const OMAN_GEO_EVIDENCE_REQUIRED_KINDS: readonly OmanGeoEvidenceKind[] = [
  'provider-inventory',
  'editorial-content',
  'qa-evidence',
  'promotion-review',
] as const;

export const OMAN_GEO_EVIDENCE_REGISTRY_ENTRIES: readonly OmanGeoEvidenceRegistryEntry[] = [] as const;

export const OMAN_GEO_EVIDENCE_REGISTRY_ENTITY_CONTRACTS: readonly OmanGeoEvidenceRegistryEntityContract[] = [
  {
    entity: 'governorate',
    registryEnabled: false,
    requiredEvidenceKinds: OMAN_GEO_EVIDENCE_REQUIRED_KINDS,
    minimumApprovedEvidenceEntries: 4,
    approvedEvidenceEntries: 0,
    promotionAllowed: false,
    noindexRemovalAllowed: false,
    sitemapPromotionAllowed: false,
    jsonLdAllowed: false,
    indexPromotionAllowed: false,
  },
  {
    entity: 'wilayat',
    registryEnabled: false,
    requiredEvidenceKinds: OMAN_GEO_EVIDENCE_REQUIRED_KINDS,
    minimumApprovedEvidenceEntries: 4,
    approvedEvidenceEntries: 0,
    promotionAllowed: false,
    noindexRemovalAllowed: false,
    sitemapPromotionAllowed: false,
    jsonLdAllowed: false,
    indexPromotionAllowed: false,
  },
  {
    entity: 'area',
    registryEnabled: false,
    requiredEvidenceKinds: OMAN_GEO_EVIDENCE_REQUIRED_KINDS,
    minimumApprovedEvidenceEntries: 4,
    approvedEvidenceEntries: 0,
    promotionAllowed: false,
    noindexRemovalAllowed: false,
    sitemapPromotionAllowed: false,
    jsonLdAllowed: false,
    indexPromotionAllowed: false,
  },
] as const;

export const OMAN_GEO_EVIDENCE_REGISTRY_CONTRACT = {
  version: OMAN_GEO_EVIDENCE_REGISTRY_CONTRACT_VERSION,
  registryEnabled: false,
  entries: OMAN_GEO_EVIDENCE_REGISTRY_ENTRIES,
  entityContracts: OMAN_GEO_EVIDENCE_REGISTRY_ENTITY_CONTRACTS,
  promotionAllowed: false,
  noindexRemovalAllowed: false,
  sitemapPromotionAllowed: false,
  jsonLdAllowed: false,
  indexPromotionAllowed: false,
  nonGoals: [
    'No evidence entry is approved by this registry contract.',
    'No noindex guardrail is removed by this registry contract.',
    'No sitemap inclusion is allowed by this registry contract.',
    'No JSON-LD is generated by this registry contract.',
    'No geo route becomes indexable by this registry contract.',
    'No runtime provider or editorial query is added by this registry contract.',
  ],
} as const;
