import type { OmanGeoRouteEntity } from '@/config/geo/route-contract';

export type OmanGeoPublicationGateStatus = 'blocked-readiness' | 'blocked-review' | 'blocked-evidence' | 'ready-disabled' | 'approved';
export type OmanGeoPublicationGateKey = 'noindex-removal' | 'sitemap-promotion' | 'json-ld' | 'index-promotion';

export type OmanGeoPublicationGateRequirement = {
  key: 'readiness-complete' | 'review-approved' | 'evidence-approved' | 'technical-gate-enabled';
  description: string;
  required: boolean;
  complete: boolean;
};

export type OmanGeoPublicationGateEntityContract = {
  entity: OmanGeoRouteEntity;
  status: OmanGeoPublicationGateStatus;
  publicationGateEnabled: boolean;
  noindexRemovalAllowed: boolean;
  sitemapPromotionAllowed: boolean;
  jsonLdAllowed: boolean;
  indexPromotionAllowed: boolean;
  allowedGateKeys: readonly OmanGeoPublicationGateKey[];
  requirements: readonly OmanGeoPublicationGateRequirement[];
};

export const OMAN_GEO_PUBLICATION_GATES_CONTRACT_VERSION = 'v1' as const;

const sharedPublicationGateRequirements = [
  {
    key: 'readiness-complete',
    description: 'Unified readiness must be complete before publication gates can open.',
    required: true,
    complete: false,
  },
  {
    key: 'review-approved',
    description: 'Promotion review must be approved by a human reviewer before publication gates can open.',
    required: true,
    complete: false,
  },
  {
    key: 'evidence-approved',
    description: 'Provider, editorial, QA and review evidence must be approved before publication gates can open.',
    required: true,
    complete: false,
  },
  {
    key: 'technical-gate-enabled',
    description: 'A separate technical gate must explicitly enable each publication surface.',
    required: true,
    complete: false,
  },
] as const satisfies readonly OmanGeoPublicationGateRequirement[];

export const OMAN_GEO_PUBLICATION_GATE_ENTITY_CONTRACTS: readonly OmanGeoPublicationGateEntityContract[] = [
  {
    entity: 'governorate',
    status: 'blocked-readiness',
    publicationGateEnabled: false,
    noindexRemovalAllowed: false,
    sitemapPromotionAllowed: false,
    jsonLdAllowed: false,
    indexPromotionAllowed: false,
    allowedGateKeys: [] as const,
    requirements: sharedPublicationGateRequirements,
  },
  {
    entity: 'wilayat',
    status: 'blocked-readiness',
    publicationGateEnabled: false,
    noindexRemovalAllowed: false,
    sitemapPromotionAllowed: false,
    jsonLdAllowed: false,
    indexPromotionAllowed: false,
    allowedGateKeys: [] as const,
    requirements: sharedPublicationGateRequirements,
  },
  {
    entity: 'area',
    status: 'blocked-readiness',
    publicationGateEnabled: false,
    noindexRemovalAllowed: false,
    sitemapPromotionAllowed: false,
    jsonLdAllowed: false,
    indexPromotionAllowed: false,
    allowedGateKeys: [] as const,
    requirements: sharedPublicationGateRequirements,
  },
] as const;

export const OMAN_GEO_PUBLICATION_GATES_CONTRACT = {
  version: OMAN_GEO_PUBLICATION_GATES_CONTRACT_VERSION,
  status: 'blocked-readiness' as OmanGeoPublicationGateStatus,
  contracts: OMAN_GEO_PUBLICATION_GATE_ENTITY_CONTRACTS,
  publicationGateEnabled: false,
  noindexRemovalAllowed: false,
  sitemapPromotionAllowed: false,
  jsonLdAllowed: false,
  indexPromotionAllowed: false,
  nonGoals: [
    'No noindex guardrail is removed by this publication gate contract.',
    'No sitemap inclusion is allowed by this publication gate contract.',
    'No JSON-LD is generated by this publication gate contract.',
    'No geo route becomes indexable by this publication gate contract.',
    'No runtime provider or editorial query is added by this publication gate contract.',
  ],
} as const;
