import type { OmanGeoRouteEntity } from '@/config/geo/route-contract';

export type OmanGeoQaEvidenceStatus = 'contract-only' | 'ready-for-review' | 'approved';

export type OmanGeoQaEvidenceKey =
  | 'canonical-review'
  | 'hreflang-review'
  | 'thin-page-review'
  | 'sitemap-policy-review'
  | 'promotion-pr-approval';

export type OmanGeoQaEvidenceRequirement = {
  key: OmanGeoQaEvidenceKey;
  description: string;
  required: boolean;
  complete: boolean;
};

export type OmanGeoQaEvidenceEntityContract = {
  entity: OmanGeoRouteEntity;
  status: OmanGeoQaEvidenceStatus;
  requiresCanonicalReview: boolean;
  requiresHreflangReview: boolean;
  requiresThinPageReview: boolean;
  requiresSitemapPolicyReview: boolean;
  requiresPromotionPrApproval: boolean;
  canonicalReviewComplete: boolean;
  hreflangReviewComplete: boolean;
  thinPageReviewComplete: boolean;
  sitemapPolicyReviewComplete: boolean;
  promotionPrApproved: boolean;
  noindexRemovalAllowed: boolean;
  sitemapPromotionAllowed: boolean;
  jsonLdAllowed: boolean;
  indexPromotionAllowed: boolean;
  requirements: readonly OmanGeoQaEvidenceRequirement[];
};

export const OMAN_GEO_QA_EVIDENCE_CONTRACT_VERSION = 'v1' as const;

const sharedQaEvidenceRequirements = [
  {
    key: 'canonical-review',
    description: 'Canonical behavior must be reviewed for the localized geo page pair.',
    required: true,
    complete: false,
  },
  {
    key: 'hreflang-review',
    description: 'Hreflang behavior must be reviewed for English and Arabic geo page variants.',
    required: true,
    complete: false,
  },
  {
    key: 'thin-page-review',
    description: 'Thin-page risk must be reviewed before noindex can be removed.',
    required: true,
    complete: false,
  },
  {
    key: 'sitemap-policy-review',
    description: 'Sitemap policy must be reviewed before sitemap inclusion is allowed.',
    required: true,
    complete: false,
  },
  {
    key: 'promotion-pr-approval',
    description: 'Index promotion must happen in a separate approved PR.',
    required: true,
    complete: false,
  },
] as const satisfies readonly OmanGeoQaEvidenceRequirement[];

export const OMAN_GEO_QA_EVIDENCE_CONTRACTS: readonly OmanGeoQaEvidenceEntityContract[] = [
  {
    entity: 'governorate',
    status: 'contract-only',
    requiresCanonicalReview: true,
    requiresHreflangReview: true,
    requiresThinPageReview: true,
    requiresSitemapPolicyReview: true,
    requiresPromotionPrApproval: true,
    canonicalReviewComplete: false,
    hreflangReviewComplete: false,
    thinPageReviewComplete: false,
    sitemapPolicyReviewComplete: false,
    promotionPrApproved: false,
    noindexRemovalAllowed: false,
    sitemapPromotionAllowed: false,
    jsonLdAllowed: false,
    indexPromotionAllowed: false,
    requirements: sharedQaEvidenceRequirements,
  },
  {
    entity: 'wilayat',
    status: 'contract-only',
    requiresCanonicalReview: true,
    requiresHreflangReview: true,
    requiresThinPageReview: true,
    requiresSitemapPolicyReview: true,
    requiresPromotionPrApproval: true,
    canonicalReviewComplete: false,
    hreflangReviewComplete: false,
    thinPageReviewComplete: false,
    sitemapPolicyReviewComplete: false,
    promotionPrApproved: false,
    noindexRemovalAllowed: false,
    sitemapPromotionAllowed: false,
    jsonLdAllowed: false,
    indexPromotionAllowed: false,
    requirements: sharedQaEvidenceRequirements,
  },
  {
    entity: 'area',
    status: 'contract-only',
    requiresCanonicalReview: true,
    requiresHreflangReview: true,
    requiresThinPageReview: true,
    requiresSitemapPolicyReview: true,
    requiresPromotionPrApproval: true,
    canonicalReviewComplete: false,
    hreflangReviewComplete: false,
    thinPageReviewComplete: false,
    sitemapPolicyReviewComplete: false,
    promotionPrApproved: false,
    noindexRemovalAllowed: false,
    sitemapPromotionAllowed: false,
    jsonLdAllowed: false,
    indexPromotionAllowed: false,
    requirements: sharedQaEvidenceRequirements,
  },
] as const;

export const OMAN_GEO_QA_EVIDENCE_CONTRACT = {
  version: OMAN_GEO_QA_EVIDENCE_CONTRACT_VERSION,
  status: 'contract-only' as OmanGeoQaEvidenceStatus,
  contracts: OMAN_GEO_QA_EVIDENCE_CONTRACTS,
  currentQaEvidenceAvailable: false,
  noindexRemovalAllowed: false,
  sitemapPromotionAllowed: false,
  jsonLdAllowed: false,
  indexPromotionAllowed: false,
  promotionRequiresApprovedPr: true,
  nonGoals: [
    'No noindex guardrail is removed by this contract.',
    'No sitemap inclusion is allowed by this contract.',
    'No JSON-LD is generated by this contract.',
    'No geo route becomes indexable by this contract.',
    'No runtime provider or editorial query is added by this contract.',
  ],
} as const;
