import type { OmanGeoRouteEntity } from '@/config/geo/route-contract';

export type OmanGeoReadinessStatus = 'blocked-evidence-missing' | 'ready-for-review' | 'approved';

export type OmanGeoReadinessSignalKey =
  | 'provider-inventory'
  | 'editorial-content'
  | 'qa-evidence'
  | 'index-promotion-eligibility';

export type OmanGeoReadinessSignal = {
  key: OmanGeoReadinessSignalKey;
  description: string;
  required: boolean;
  complete: boolean;
};

export type OmanGeoReadinessEntityContract = {
  entity: OmanGeoRouteEntity;
  status: OmanGeoReadinessStatus;
  requiresProviderInventory: boolean;
  requiresEditorialContent: boolean;
  requiresQaEvidence: boolean;
  requiresIndexPromotionEligibility: boolean;
  providerInventoryReady: boolean;
  editorialContentReady: boolean;
  qaEvidenceReady: boolean;
  indexPromotionEligibilityReady: boolean;
  readyForPromotionReview: boolean;
  noindexRemovalAllowed: boolean;
  sitemapPromotionAllowed: boolean;
  jsonLdAllowed: boolean;
  indexPromotionAllowed: boolean;
  signals: readonly OmanGeoReadinessSignal[];
};

export const OMAN_GEO_READINESS_CONTRACT_VERSION = 'v1' as const;

const sharedReadinessSignals = [
  {
    key: 'provider-inventory',
    description: 'Published provider inventory must meet the entity threshold before promotion review.',
    required: true,
    complete: false,
  },
  {
    key: 'editorial-content',
    description: 'Localized human-reviewed editorial content must exist before promotion review.',
    required: true,
    complete: false,
  },
  {
    key: 'qa-evidence',
    description: 'Canonical, hreflang, thin-page, sitemap policy and promotion PR QA evidence must be complete.',
    required: true,
    complete: false,
  },
  {
    key: 'index-promotion-eligibility',
    description: 'The central index promotion eligibility gate must approve review readiness.',
    required: true,
    complete: false,
  },
] as const satisfies readonly OmanGeoReadinessSignal[];

export const OMAN_GEO_READINESS_ENTITY_CONTRACTS: readonly OmanGeoReadinessEntityContract[] = [
  {
    entity: 'governorate',
    status: 'blocked-evidence-missing',
    requiresProviderInventory: true,
    requiresEditorialContent: true,
    requiresQaEvidence: true,
    requiresIndexPromotionEligibility: true,
    providerInventoryReady: false,
    editorialContentReady: false,
    qaEvidenceReady: false,
    indexPromotionEligibilityReady: false,
    readyForPromotionReview: false,
    noindexRemovalAllowed: false,
    sitemapPromotionAllowed: false,
    jsonLdAllowed: false,
    indexPromotionAllowed: false,
    signals: sharedReadinessSignals,
  },
  {
    entity: 'wilayat',
    status: 'blocked-evidence-missing',
    requiresProviderInventory: true,
    requiresEditorialContent: true,
    requiresQaEvidence: true,
    requiresIndexPromotionEligibility: true,
    providerInventoryReady: false,
    editorialContentReady: false,
    qaEvidenceReady: false,
    indexPromotionEligibilityReady: false,
    readyForPromotionReview: false,
    noindexRemovalAllowed: false,
    sitemapPromotionAllowed: false,
    jsonLdAllowed: false,
    indexPromotionAllowed: false,
    signals: sharedReadinessSignals,
  },
  {
    entity: 'area',
    status: 'blocked-evidence-missing',
    requiresProviderInventory: true,
    requiresEditorialContent: true,
    requiresQaEvidence: true,
    requiresIndexPromotionEligibility: true,
    providerInventoryReady: false,
    editorialContentReady: false,
    qaEvidenceReady: false,
    indexPromotionEligibilityReady: false,
    readyForPromotionReview: false,
    noindexRemovalAllowed: false,
    sitemapPromotionAllowed: false,
    jsonLdAllowed: false,
    indexPromotionAllowed: false,
    signals: sharedReadinessSignals,
  },
] as const;

export const OMAN_GEO_READINESS_CONTRACT = {
  version: OMAN_GEO_READINESS_CONTRACT_VERSION,
  status: 'blocked-evidence-missing' as OmanGeoReadinessStatus,
  contracts: OMAN_GEO_READINESS_ENTITY_CONTRACTS,
  readyForPromotionReview: false,
  noindexRemovalAllowed: false,
  sitemapPromotionAllowed: false,
  jsonLdAllowed: false,
  indexPromotionAllowed: false,
  nonGoals: [
    'No noindex guardrail is removed by this readiness contract.',
    'No sitemap inclusion is allowed by this readiness contract.',
    'No JSON-LD is generated by this readiness contract.',
    'No geo route becomes indexable by this readiness contract.',
    'No runtime provider or editorial query is added by this readiness contract.',
  ],
} as const;
