export type OmanGeoRouteLocale = 'en' | 'ar';

export type OmanGeoRouteCountry = 'om';

export type OmanGeoRouteEntity = 'governorate' | 'wilayat' | 'area';

export type OmanGeoRouteContractStatus = 'planned-only' | 'runtime-scaffold' | 'metadata-noindex' | 'runtime-enabled';

export type OmanGeoRouteTemplate = {
  routeName: string;
  entity: OmanGeoRouteEntity;
  pathTemplate: string;
  routeFile: string;
  locales: readonly OmanGeoRouteLocale[];
  country: OmanGeoRouteCountry;
  runtimeEnabled: boolean;
  metadataEnabled: boolean;
  noindexEnabled: boolean;
  sitemapEnabled: boolean;
  jsonLdEnabled: boolean;
  hasHreflangPeer: boolean;
  compatibilityOnly: boolean;
  indexableCanonical: boolean;
  canonicalReplacementPathTemplate: string;
};

export const OMAN_GEO_ROUTE_CONTRACT_VERSION = 'v4' as const;

export const OMAN_GEO_ROUTE_TEMPLATES: readonly OmanGeoRouteTemplate[] = [
  {
    routeName: 'oman-governorate',
    entity: 'governorate',
    pathTemplate: '/[locale]/[country]/oman/governorates/[governorateSlug]',
    routeFile: 'src/app/[locale]/[country]/oman/governorates/[governorateSlug]/page.tsx',
    locales: ['en', 'ar'],
    country: 'om',
    runtimeEnabled: true,
    metadataEnabled: true,
    noindexEnabled: true,
    sitemapEnabled: false,
    jsonLdEnabled: false,
    hasHreflangPeer: true,
    compatibilityOnly: true,
    indexableCanonical: false,
    canonicalReplacementPathTemplate: '/[locale]/[country]/locations/[governorateSlug]',
  },
  {
    routeName: 'oman-wilayat',
    entity: 'wilayat',
    pathTemplate: '/[locale]/[country]/oman/wilayats/[wilayatSlug]',
    routeFile: 'src/app/[locale]/[country]/oman/wilayats/[wilayatSlug]/page.tsx',
    locales: ['en', 'ar'],
    country: 'om',
    runtimeEnabled: true,
    metadataEnabled: true,
    noindexEnabled: true,
    sitemapEnabled: false,
    jsonLdEnabled: false,
    hasHreflangPeer: true,
    compatibilityOnly: true,
    indexableCanonical: false,
    canonicalReplacementPathTemplate: '/[locale]/[country]/locations/[governorateSlug]/[wilayatSlug]',
  },
  {
    routeName: 'oman-area',
    entity: 'area',
    pathTemplate: '/[locale]/[country]/oman/areas/[areaSlug]',
    routeFile: 'src/app/[locale]/[country]/oman/areas/[areaSlug]/page.tsx',
    locales: ['en', 'ar'],
    country: 'om',
    runtimeEnabled: true,
    metadataEnabled: true,
    noindexEnabled: true,
    sitemapEnabled: false,
    jsonLdEnabled: false,
    hasHreflangPeer: true,
    compatibilityOnly: true,
    indexableCanonical: false,
    canonicalReplacementPathTemplate: '/[locale]/[country]/locations/[governorateSlug]/[wilayatSlug]/[areaSlug]',
  },
] as const;

export const OMAN_GEO_ROUTE_CONTRACT = {
  version: OMAN_GEO_ROUTE_CONTRACT_VERSION,
  status: 'metadata-noindex' as OmanGeoRouteContractStatus,
  runtimeRoutesEnabled: true,
  metadataEnabled: true,
  noindexEnabled: true,
  sitemapEnabled: false,
  jsonLdEnabled: false,
  routeTemplates: OMAN_GEO_ROUTE_TEMPLATES,
  canonicalSource: 'src/config/geo/oman.ts',
  canonicalReplacementFamily: '/[locale]/[country]/locations/...',
  nonGoals: [
    'No sitemap entries are generated by this scaffold.',
    'No JSON-LD is generated by this scaffold.',
    'No provider data is queried by this scaffold.',
    'No database access is added by this scaffold.',
    'No geo page is indexable yet.',
    'Legacy Oman geo routes are compatibility-only and must not become indexable canonical pages.',
  ],
} as const;
