export type OmanGeoRouteLocale = 'en-OM' | 'ar-OM';

export type OmanGeoRouteEntity = 'governorate' | 'wilayat' | 'area';

export type OmanGeoRouteContractStatus = 'planned-only' | 'runtime-enabled';

export type OmanGeoRouteTemplate = {
  routeName: string;
  locale: OmanGeoRouteLocale;
  entity: OmanGeoRouteEntity;
  pathTemplate: string;
  runtimeEnabled: boolean;
  hasHreflangPeer: boolean;
};

export const OMAN_GEO_ROUTE_CONTRACT_VERSION = 'v1' as const;

export const OMAN_GEO_ROUTE_TEMPLATES: readonly OmanGeoRouteTemplate[] = [
  {
    routeName: 'oman-governorate-en',
    locale: 'en-OM',
    entity: 'governorate',
    pathTemplate: '/en-om/oman/governorates/[governorateSlug]',
    runtimeEnabled: false,
    hasHreflangPeer: true,
  },
  {
    routeName: 'oman-governorate-ar',
    locale: 'ar-OM',
    entity: 'governorate',
    pathTemplate: '/ar-om/oman/governorates/[governorateSlug]',
    runtimeEnabled: false,
    hasHreflangPeer: true,
  },
  {
    routeName: 'oman-wilayat-en',
    locale: 'en-OM',
    entity: 'wilayat',
    pathTemplate: '/en-om/oman/wilayats/[wilayatSlug]',
    runtimeEnabled: false,
    hasHreflangPeer: true,
  },
  {
    routeName: 'oman-wilayat-ar',
    locale: 'ar-OM',
    entity: 'wilayat',
    pathTemplate: '/ar-om/oman/wilayats/[wilayatSlug]',
    runtimeEnabled: false,
    hasHreflangPeer: true,
  },
  {
    routeName: 'oman-area-en',
    locale: 'en-OM',
    entity: 'area',
    pathTemplate: '/en-om/oman/areas/[areaSlug]',
    runtimeEnabled: false,
    hasHreflangPeer: true,
  },
  {
    routeName: 'oman-area-ar',
    locale: 'ar-OM',
    entity: 'area',
    pathTemplate: '/ar-om/oman/areas/[areaSlug]',
    runtimeEnabled: false,
    hasHreflangPeer: true,
  },
] as const;

export const OMAN_GEO_ROUTE_CONTRACT = {
  version: OMAN_GEO_ROUTE_CONTRACT_VERSION,
  status: 'planned-only' as OmanGeoRouteContractStatus,
  runtimeRoutesEnabled: false,
  routeTemplates: OMAN_GEO_ROUTE_TEMPLATES,
  canonicalSource: 'src/config/geo/oman.ts',
  nonGoals: [
    'No Next.js route files are added by this contract.',
    'No sitemap entries are generated by this contract.',
    'No metadata or JSON-LD is generated by this contract.',
    'No provider data is queried by this contract.',
  ],
} as const;
