import type { LicenseRequirementLevel, TaxonomyRegistryItemBase } from './types';

export type DoctorLevel = TaxonomyRegistryItemBase & { readonly isMedicalDoctor: boolean; readonly isDental: boolean; readonly isMentalHealth: boolean; readonly requiresLicense: LicenseRequirementLevel; readonly requiresQualification: boolean };

export const doctorLevels = [
  { slug: 'general-practitioner', labelEn: 'General Practitioner', labelAr: 'طبيب عام', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'General Practitioner practitioner level for profile classification.', descriptionAr: 'مستوى مهني لتصنيف الطبيب العام.', isMedicalDoctor: true, isDental: false, isMentalHealth: false, requiresLicense: 'required', requiresQualification: true },
  { slug: 'family-doctor', labelEn: 'Family Doctor', labelAr: 'طبيب أسرة', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Family Doctor practitioner level for profile classification.', descriptionAr: 'مستوى مهني لتصنيف طبيب الأسرة.', isMedicalDoctor: true, isDental: false, isMentalHealth: false, requiresLicense: 'required', requiresQualification: true },
  { slug: 'specialist', labelEn: 'Specialist', labelAr: 'اختصاصي', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Specialist practitioner level for profile classification.', descriptionAr: 'مستوى مهني لتصنيف الطبيب الاختصاصي.', isMedicalDoctor: true, isDental: false, isMentalHealth: false, requiresLicense: 'required', requiresQualification: true },
  { slug: 'consultant', labelEn: 'Consultant', labelAr: 'استشاري', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Consultant practitioner level for profile classification.', descriptionAr: 'مستوى مهني لتصنيف الطبيب الاستشاري.', isMedicalDoctor: true, isDental: false, isMentalHealth: false, requiresLicense: 'required', requiresQualification: true },
  { slug: 'senior-consultant', labelEn: 'Senior Consultant', labelAr: 'استشاري أول', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Senior Consultant practitioner level for profile classification.', descriptionAr: 'مستوى مهني لتصنيف الاستشاري الأول.', isMedicalDoctor: true, isDental: false, isMentalHealth: false, requiresLicense: 'required', requiresQualification: true },
  { slug: 'subspecialist', labelEn: 'Subspecialist', labelAr: 'اختصاصي دقيق', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Subspecialist practitioner level for profile classification.', descriptionAr: 'مستوى مهني لتصنيف الاختصاصي الدقيق.', isMedicalDoctor: true, isDental: false, isMentalHealth: false, requiresLicense: 'required', requiresQualification: true },
  { slug: 'surgeon', labelEn: 'Surgeon', labelAr: 'جراح', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Surgeon practitioner level for profile classification.', descriptionAr: 'مستوى مهني لتصنيف الطبيب الجراح.', isMedicalDoctor: true, isDental: false, isMentalHealth: false, requiresLicense: 'required', requiresQualification: true },
  { slug: 'dentist', labelEn: 'Dentist', labelAr: 'طبيب أسنان', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Dentist practitioner level for profile classification.', descriptionAr: 'مستوى مهني لتصنيف طبيب الأسنان.', isMedicalDoctor: false, isDental: true, isMentalHealth: false, requiresLicense: 'required', requiresQualification: true },
  { slug: 'orthodontist', labelEn: 'Orthodontist', labelAr: 'اختصاصي تقويم الأسنان', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Orthodontist practitioner level for profile classification.', descriptionAr: 'مستوى مهني لتصنيف اختصاصي تقويم الأسنان.', isMedicalDoctor: false, isDental: true, isMentalHealth: false, requiresLicense: 'required', requiresQualification: true },
  { slug: 'oral-surgeon', labelEn: 'Oral Surgeon', labelAr: 'جراح الفم', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Oral Surgeon practitioner level for profile classification.', descriptionAr: 'مستوى مهني لتصنيف جراح الفم.', isMedicalDoctor: false, isDental: true, isMentalHealth: false, requiresLicense: 'required', requiresQualification: true },
  { slug: 'psychiatrist', labelEn: 'Psychiatrist', labelAr: 'طبيب نفسي', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Psychiatrist practitioner level for profile classification.', descriptionAr: 'مستوى مهني لتصنيف الطبيب النفسي.', isMedicalDoctor: true, isDental: false, isMentalHealth: true, requiresLicense: 'required', requiresQualification: true },
  { slug: 'psychologist', labelEn: 'Psychologist', labelAr: 'أخصائي نفسي', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Psychologist practitioner level for profile classification.', descriptionAr: 'مستوى مهني لتصنيف الأخصائي النفسي.', isMedicalDoctor: false, isDental: false, isMentalHealth: true, requiresLicense: 'required', requiresQualification: true },
  { slug: 'counselor', labelEn: 'Counselor', labelAr: 'مرشد نفسي', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Counselor practitioner level for profile classification.', descriptionAr: 'مستوى مهني لتصنيف المرشد النفسي.', isMedicalDoctor: false, isDental: false, isMentalHealth: true, requiresLicense: 'required', requiresQualification: true },
  { slug: 'therapist', labelEn: 'Therapist', labelAr: 'معالج', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Therapist practitioner level for profile classification.', descriptionAr: 'مستوى مهني لتصنيف المعالج.', isMedicalDoctor: false, isDental: false, isMentalHealth: true, requiresLicense: 'required', requiresQualification: true },
  { slug: 'physiotherapist', labelEn: 'Physiotherapist', labelAr: 'أخصائي علاج طبيعي', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Physiotherapist practitioner level for profile classification.', descriptionAr: 'مستوى مهني لتصنيف أخصائي العلاج الطبيعي.', isMedicalDoctor: false, isDental: false, isMentalHealth: false, requiresLicense: 'required', requiresQualification: true },
  { slug: 'dietitian', labelEn: 'Dietitian', labelAr: 'أخصائي تغذية', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Dietitian practitioner level for profile classification.', descriptionAr: 'مستوى مهني لتصنيف أخصائي التغذية.', isMedicalDoctor: false, isDental: false, isMentalHealth: false, requiresLicense: 'required', requiresQualification: true },
  { slug: 'radiologist', labelEn: 'Radiologist', labelAr: 'طبيب أشعة', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Radiologist practitioner level for profile classification.', descriptionAr: 'مستوى مهني لتصنيف طبيب الأشعة.', isMedicalDoctor: true, isDental: false, isMentalHealth: false, requiresLicense: 'required', requiresQualification: true },
  { slug: 'laboratory-medicine-specialist', labelEn: 'Laboratory Medicine Specialist', labelAr: 'اختصاصي طب المختبرات', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Laboratory Medicine Specialist practitioner level for profile classification.', descriptionAr: 'مستوى مهني لتصنيف اختصاصي طب المختبرات.', isMedicalDoctor: true, isDental: false, isMentalHealth: false, requiresLicense: 'required', requiresQualification: true },
] as const satisfies readonly DoctorLevel[];

export type DoctorLevelSlug = (typeof doctorLevels)[number]['slug'];
