import type { LicenseRequirementLevel, TaxonomyRegistryItemBase } from './types';

export type DoctorLevel = TaxonomyRegistryItemBase & { readonly isMedicalDoctor: boolean; readonly isDental: boolean; readonly isMentalHealth: boolean; readonly requiresLicense: LicenseRequirementLevel; readonly requiresQualification: boolean };

export const doctorLevels = [
  { slug: 'general-practitioner', labelEn: 'General Practitioner', labelAr: 'عام ممارس', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'General Practitioner practitioner level for profile classification.', descriptionAr: 'General Practitioner مستوى مهني للتصنيف.', isMedicalDoctor: true, isDental: false, isMentalHealth: false, requiresLicense: 'required', requiresQualification: true },
  { slug: 'family-doctor', labelEn: 'Family Doctor', labelAr: 'أسرة طبيب', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Family Doctor practitioner level for profile classification.', descriptionAr: 'Family Doctor مستوى مهني للتصنيف.', isMedicalDoctor: true, isDental: false, isMentalHealth: false, requiresLicense: 'required', requiresQualification: true },
  { slug: 'specialist', labelEn: 'Specialist', labelAr: 'اختصاصي', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Specialist practitioner level for profile classification.', descriptionAr: 'Specialist مستوى مهني للتصنيف.', isMedicalDoctor: true, isDental: false, isMentalHealth: false, requiresLicense: 'required', requiresQualification: true },
  { slug: 'consultant', labelEn: 'Consultant', labelAr: 'استشاري', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Consultant practitioner level for profile classification.', descriptionAr: 'Consultant مستوى مهني للتصنيف.', isMedicalDoctor: true, isDental: false, isMentalHealth: false, requiresLicense: 'required', requiresQualification: true },
  { slug: 'senior-consultant', labelEn: 'Senior Consultant', labelAr: 'كبير استشاري', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Senior Consultant practitioner level for profile classification.', descriptionAr: 'Senior Consultant مستوى مهني للتصنيف.', isMedicalDoctor: true, isDental: false, isMentalHealth: false, requiresLicense: 'required', requiresQualification: true },
  { slug: 'subspecialist', labelEn: 'Subspecialist', labelAr: 'اختصاصي دقيق', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Subspecialist practitioner level for profile classification.', descriptionAr: 'Subspecialist مستوى مهني للتصنيف.', isMedicalDoctor: true, isDental: false, isMentalHealth: false, requiresLicense: 'required', requiresQualification: true },
  { slug: 'surgeon', labelEn: 'Surgeon', labelAr: 'جراح', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Surgeon practitioner level for profile classification.', descriptionAr: 'Surgeon مستوى مهني للتصنيف.', isMedicalDoctor: true, isDental: false, isMentalHealth: false, requiresLicense: 'required', requiresQualification: true },
  { slug: 'dentist', labelEn: 'Dentist', labelAr: 'طبيب أسنان', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Dentist practitioner level for profile classification.', descriptionAr: 'Dentist مستوى مهني للتصنيف.', isMedicalDoctor: false, isDental: true, isMentalHealth: false, requiresLicense: 'required', requiresQualification: true },
  { slug: 'orthodontist', labelEn: 'Orthodontist', labelAr: 'orthodontist', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Orthodontist practitioner level for profile classification.', descriptionAr: 'Orthodontist مستوى مهني للتصنيف.', isMedicalDoctor: false, isDental: true, isMentalHealth: false, requiresLicense: 'required', requiresQualification: true },
  { slug: 'oral-surgeon', labelEn: 'Oral Surgeon', labelAr: 'فم جراح', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Oral Surgeon practitioner level for profile classification.', descriptionAr: 'Oral Surgeon مستوى مهني للتصنيف.', isMedicalDoctor: false, isDental: true, isMentalHealth: false, requiresLicense: 'required', requiresQualification: true },
  { slug: 'psychiatrist', labelEn: 'Psychiatrist', labelAr: 'طبيب نفسي', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Psychiatrist practitioner level for profile classification.', descriptionAr: 'Psychiatrist مستوى مهني للتصنيف.', isMedicalDoctor: true, isDental: false, isMentalHealth: true, requiresLicense: 'required', requiresQualification: true },
  { slug: 'psychologist', labelEn: 'Psychologist', labelAr: 'أخصائي نفسي', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Psychologist practitioner level for profile classification.', descriptionAr: 'Psychologist مستوى مهني للتصنيف.', isMedicalDoctor: false, isDental: false, isMentalHealth: true, requiresLicense: 'required', requiresQualification: true },
  { slug: 'counselor', labelEn: 'Counselor', labelAr: 'مرشد', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Counselor practitioner level for profile classification.', descriptionAr: 'Counselor مستوى مهني للتصنيف.', isMedicalDoctor: false, isDental: false, isMentalHealth: true, requiresLicense: 'required', requiresQualification: true },
  { slug: 'therapist', labelEn: 'Therapist', labelAr: 'معالج', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Therapist practitioner level for profile classification.', descriptionAr: 'Therapist مستوى مهني للتصنيف.', isMedicalDoctor: false, isDental: false, isMentalHealth: true, requiresLicense: 'required', requiresQualification: true },
  { slug: 'physiotherapist', labelEn: 'Physiotherapist', labelAr: 'physiotherapist', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Physiotherapist practitioner level for profile classification.', descriptionAr: 'Physiotherapist مستوى مهني للتصنيف.', isMedicalDoctor: false, isDental: false, isMentalHealth: false, requiresLicense: 'required', requiresQualification: true },
  { slug: 'dietitian', labelEn: 'Dietitian', labelAr: 'اختصاصي تغذية', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Dietitian practitioner level for profile classification.', descriptionAr: 'Dietitian مستوى مهني للتصنيف.', isMedicalDoctor: false, isDental: false, isMentalHealth: false, requiresLicense: 'required', requiresQualification: true },
  { slug: 'radiologist', labelEn: 'Radiologist', labelAr: 'اختصاصي أشعة', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Radiologist practitioner level for profile classification.', descriptionAr: 'Radiologist مستوى مهني للتصنيف.', isMedicalDoctor: true, isDental: false, isMentalHealth: false, requiresLicense: 'required', requiresQualification: true },
  { slug: 'laboratory-medicine-specialist', labelEn: 'Laboratory Medicine Specialist', labelAr: 'مختبر طب اختصاصي', scope: 'core', publicLaunchPhase: 1, descriptionEn: 'Laboratory Medicine Specialist practitioner level for profile classification.', descriptionAr: 'Laboratory Medicine Specialist مستوى مهني للتصنيف.', isMedicalDoctor: true, isDental: false, isMentalHealth: false, requiresLicense: 'required', requiresQualification: true },
] as const satisfies readonly DoctorLevel[];

export type DoctorLevelSlug = (typeof doctorLevels)[number]['slug'];
